name = "socialiser"
main = ".open-next/worker.js"
compatibility_date = "2025-05-05"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
CRON_SECRET = "socialiser-cron-2026"
THREADS_APP_ID = "1299493258747441"
THREADS_APP_SECRET = "053e2e8e7cc884c90e11f73a73a9733e"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "socialiser"
